
import javax.swing.ImageIcon;

/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
/**
 *
 * @author peckfarl
 */
public class DasFrame extends javax.swing.JFrame {

    String word = "";
    String lettersGuessed = "";
    String letGuess = "";
    int lives = 6;
    String wordBak = "";

    /**
     * Creates new form DasFrame
     */
    public DasFrame() {
        initComponents();
        chooseWord();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPic = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnQuit = new javax.swing.JButton();
        lblGuess = new javax.swing.JLabel();
        lblGuessWord = new javax.swing.JLabel();
        txtGuess = new javax.swing.JTextField();
        txtGuessWord = new javax.swing.JTextField();
        btnGuess = new javax.swing.JButton();
        btnGuessWord = new javax.swing.JButton();
        lbl0 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lblCorrectLetters = new javax.swing.JLabel();
        lblGuessed = new javax.swing.JLabel();
        lblGuessed1 = new javax.swing.JLabel();
        lblErrors = new javax.swing.JLabel();
        btnRestart = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/man6.jpg"))); // NOI18N

        lblTitle.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 102, 102));
        lblTitle.setText("HANGMAN");

        btnQuit.setText("QUIT");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        lblGuess.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblGuess.setText("Guess Letter:");

        lblGuessWord.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblGuessWord.setText("Guess Word:");

        txtGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGuessActionPerformed(evt);
            }
        });

        txtGuessWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGuessWordActionPerformed(evt);
            }
        });

        btnGuess.setText("GO");
        btnGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuessActionPerformed(evt);
            }
        });

        btnGuessWord.setText("GO");
        btnGuessWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuessWordActionPerformed(evt);
            }
        });

        lbl0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl0.setText("_");

        lbl1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl1.setText("_");

        lbl2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl2.setText("_");

        lbl3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl3.setText("_");

        lbl4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl4.setText("_");

        lblCorrectLetters.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCorrectLetters.setText("Letters Correct");

        lblGuessed.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblGuessed.setText("Letters Guessed: ");

        btnRestart.setText("Restart");
        btnRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestartActionPerformed(evt);
            }
        });

        jLabel1.setText("If picture not appearing, icons located in wrong drive");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblPic)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblGuess)
                                .addGap(4, 4, 4)
                                .addComponent(txtGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btnGuess))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lblGuessWord)
                                .addGap(4, 4, 4)
                                .addComponent(txtGuessWord, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btnGuessWord))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCorrectLetters)
                                .addGap(18, 18, 18)
                                .addComponent(lbl0)
                                .addGap(6, 6, 6)
                                .addComponent(lbl1)
                                .addGap(6, 6, 6)
                                .addComponent(lbl2)
                                .addGap(6, 6, 6)
                                .addComponent(lbl3)
                                .addGap(6, 6, 6)
                                .addComponent(lbl4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblGuessed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblGuessed1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRestart, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtGuess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnGuess))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGuessWord)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtGuessWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnGuessWord))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblCorrectLetters))
                            .addComponent(lbl0)
                            .addComponent(lbl1)
                            .addComponent(lbl2)
                            .addComponent(lbl3)
                            .addComponent(lbl4))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGuessed)
                            .addComponent(lblGuessed1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblErrors, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRestart, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuessActionPerformed
        if (lives == 0) {
            lblErrors.setText("Game Over! Press restart to play again");
            System.out.println("YOU LOSE!");
        } else {

            boolean correctGuess = false;

            if (txtGuess.getText().length() != 1) {
                System.out.println("All is not well shipmate");
            } else {

                String guess = txtGuess.getText().toUpperCase();
                char letter = guess.charAt(0);
                char[] wordLetters = word.toCharArray();

                if (letGuess.contains(txtGuess.getText())) {
                } else {
                    letGuess += txtGuess.getText() + " ";
                }
                lblGuessed1.setText(letGuess);
                for (int x = 0; x < wordLetters.length; x++) {
                    if (letter == wordLetters[x]) {
                        changeLetter(x, letter);
                        correctGuess = true;
                    }
                }
                if (correctGuess == false) {
                    lives--;
                    lblPic.setIcon(new ImageIcon("../src/man" + lives + ".jpg"));

                }
            }
        }
        String lblsTogether = lbl0.getText()+lbl1.getText()+lbl2.getText()+lbl3.getText()+lbl4.getText();
        if (lblsTogether.contains(word)) {
            lblErrors.setText("You win!");
        }        
        txtGuess.setText("");


    }//GEN-LAST:event_btnGuessActionPerformed

    private void btnGuessWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuessWordActionPerformed
        String wordGuess = txtGuessWord.getText().toUpperCase();
        char[] gWord = wordGuess.toCharArray();
        if (wordGuess.contains(word)) {
            lbl0.setText("" + gWord[0]);
            lbl1.setText("" + gWord[1]);
            lbl2.setText("" + gWord[2]);
            lbl3.setText("" + gWord[3]);
            lbl4.setText("" + gWord[4]);
            lblErrors.setText("Gratz you win!");
        }
    }//GEN-LAST:event_btnGuessWordActionPerformed

    private void txtGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuessActionPerformed
        btnGuess.doClick();
    }//GEN-LAST:event_txtGuessActionPerformed

    private void txtGuessWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuessWordActionPerformed
        btnGuessWord.doClick(); //runs
    }//GEN-LAST:event_txtGuessWordActionPerformed

    private void btnRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestartActionPerformed
        chooseWord(); // new word chosen
        lettersGuessed = "";
        lives = 6;

        //reset screen
        lblErrors.setText("");
        lblPic.setIcon(new ImageIcon("../src/man6.jpg"));
        lblGuessed1.setText("");

        lbl0.setText("_");
        lbl1.setText("_");
        lbl2.setText("_");
        lbl3.setText("_");
        lbl4.setText("_");


    }//GEN-LAST:event_btnRestartActionPerformed

    private void changeLetter(int x, char letter) {
        if (x == 0) {
            lbl0.setText("" + letter);
        } else if (x == 1) {
            lbl1.setText("" + letter);
        } else if (x == 2) {
            lbl2.setText("" + letter);
        } else if (x == 3) {
            lbl3.setText("" + letter);
        } else if (x == 4) {
            lbl4.setText("" + letter);
        }
    }

    public void chooseWord() {
        while (wordBak.equals(word)) {

            int count = (int) (1 + Math.random() * 5);
            switch (count) {
                case 1:
                    word = "WORLD";
                    break;
                case 2:
                    word = "MAGIC";
                    break;
                case 3:
                    word = "STAIR";
                    break;
                case 4:
                    word = "BEARS";
                    break;
                case 5:
                    word = "THERE";
                    break;
            }
        }
        System.out.println("Your word is " + word);
        wordBak = word;
    }

    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DasFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuess;
    private javax.swing.JButton btnGuessWord;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnRestart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl0;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lblCorrectLetters;
    private javax.swing.JLabel lblErrors;
    private javax.swing.JLabel lblGuess;
    private javax.swing.JLabel lblGuessWord;
    private javax.swing.JLabel lblGuessed;
    private javax.swing.JLabel lblGuessed1;
    private javax.swing.JLabel lblPic;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtGuess;
    private javax.swing.JTextField txtGuessWord;
    // End of variables declaration//GEN-END:variables
}
